import { existsSync, readdirSync, readFileSync, statSync } from "node:fs";
import { join, relative } from "node:path";
import { fileURLToPath } from "node:url";

const PUBLIC_DIR = fileURLToPath(new URL("../server/public", import.meta.url));
const OUT = fileURLToPath(
  new URL("../server/src/public-files.gen.ts", import.meta.url),
);

type EmbeddedFile = {
  content: string;
  encoding: "utf8" | "base64";
};

function isTextAsset(path: string): boolean {
  return /\.(html|css|js|json|svg|txt|map)$/i.test(path);
}

function walk(
  dir: string,
  out: Record<string, EmbeddedFile> = {},
): Record<string, EmbeddedFile> {
  for (const name of readdirSync(dir)) {
    const p = join(dir, name);
    const st = statSync(p);
    if (st.isDirectory()) walk(p, out);
    else {
      const webPath = "/" + relative(PUBLIC_DIR, p).replace(/\\/g, "/");
      const buf = readFileSync(p);
      out[webPath] = isTextAsset(p)
        ? { content: buf.toString("utf8"), encoding: "utf8" }
        : { content: buf.toString("base64"), encoding: "base64" };
    }
  }
  return out;
}

const files = walk(PUBLIC_DIR);
const entries = Object.entries(files)
  .map(
    ([k, v]) =>
      `  ${JSON.stringify(k)}: { content: ${JSON.stringify(v.content)}, encoding: ${JSON.stringify(v.encoding)} },`,
  )
  .join("\n");

const src = `// AUTO-GENERATED by scripts/gen-public.ts — do not edit.
// Embedded frontend assets for the single-file executable.
export type EmbeddedPublicFile = {
  content: string;
  encoding: "utf8" | "base64";
};

export const PUBLIC_FILES: Record<string, EmbeddedPublicFile> = {
${entries}
};
`;

if (!existsSync(OUT) || readFileSync(OUT, "utf8") !== src) {
  await Bun.write(OUT, src);
  console.log(`embedded ${Object.keys(files).length} files -> ${OUT}`);
} else {
  console.log(`embedded public files unchanged -> ${OUT}`);
}
