const EXTENSION_LANGUAGES: Record<string, string> = {
  bat: "bat",
  cmd: "bat",
  c: "cpp",
  cc: "cpp",
  cpp: "cpp",
  cxx: "cpp",
  h: "cpp",
  hh: "cpp",
  hpp: "cpp",
  cs: "csharp",
  css: "css",
  go: "go",
  graphql: "graphql",
  gql: "graphql",
  hcl: "hcl",
  tf: "hcl",
  htm: "html",
  html: "html",
  cfg: "ini",
  conf: "ini",
  ini: "ini",
  toml: "ini",
  java: "java",
  cjs: "javascript",
  js: "javascript",
  jsx: "javascript",
  mjs: "javascript",
  json: "json",
  jsonc: "json",
  json5: "json",
  kt: "kotlin",
  kts: "kotlin",
  less: "less",
  lua: "lua",
  markdown: "markdown",
  md: "markdown",
  mdx: "markdown",
  pl: "perl",
  pm: "perl",
  php: "php",
  ps1: "powershell",
  psm1: "powershell",
  proto: "protobuf",
  py: "python",
  pyi: "python",
  r: "r",
  rb: "ruby",
  rs: "rust",
  sass: "scss",
  scss: "scss",
  bash: "shell",
  sh: "shell",
  zsh: "shell",
  fish: "shell",
  sql: "sql",
  swift: "swift",
  cts: "typescript",
  mts: "typescript",
  ts: "typescript",
  tsx: "typescript",
  svg: "xml",
  xml: "xml",
  yaml: "yaml",
  yml: "yaml",
};

const FILENAME_LANGUAGES: Record<string, string> = {
  dockerfile: "dockerfile",
  containerfile: "dockerfile",
  ".bashrc": "shell",
  ".zshrc": "shell",
  ".profile": "shell",
  ".gitconfig": "ini",
  ".editorconfig": "ini",
};

/** Map a file path to one of the grammars registered in monacoSetup. */
export function monacoLanguageForPath(path: string): string {
  const name = (path.split(/[\\/]/).pop() ?? "").toLowerCase();
  const byName = FILENAME_LANGUAGES[name];
  if (byName) return byName;
  if (name.startsWith("dockerfile.")) return "dockerfile";
  const extension = name.includes(".") ? (name.split(".").pop() ?? "") : "";
  return EXTENSION_LANGUAGES[extension] ?? "plaintext";
}
